# Generated by Django 4.2.5 on 2024-04-02 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orientation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='University',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=datetime.datetime(2024, 4, 2, 11, 38, 49, 828323, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2024, 4, 2, 11, 39, 13, 495539, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
    ]
